// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package v2

type Currently struct {
	Summary           string  `json:"summary"`
	Temperature       float64 `json:"temperature"`
	Humidity          float64 `json:"humidity"`
	WindSpeed         float64 `json:"windSpeed"`
	PrecipProbability float64 `json:"precipProbability"`
}

type Forecast struct {
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	Name      string    `json:"name"`
	Timezone  string    `json:"timezone"`
	Currently Currently `json:"currently"`
}

type ForecastInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Lang      string  `json:"lang"`
}
