apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: opendata
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
        tier: frontend
        version: v0.0.2
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: rodrwan/frontend:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: http-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: opendata
  labels:
    run: frontend
    tier: frontend
spec:
  ports:
  - name: http-frontend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: frontend
    tier: frontend