apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: opendata
spec:
  selector:
    matchLabels:
      run: graphql
  replicas: 1
  template:
    metadata:
      labels:
        run: graphql
        tier: backend
        version: v0.0.2
    spec:
      restartPolicy: Always
      containers:
      - name: graphql
        image: rodrwan/graphql:v0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
          name: http-graphql
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-graphql
          initialDelaySeconds: 10
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: opendata
  labels:
    run: graphql
    tier: backend
spec:
  ports:
  - name: http-graphql
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    run: graphql
    tier: backend